# Generated by Django 5.1.6 on 2025-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapChieuPhim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_rap', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='rap_images/')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
