# Generated by Django 5.1.6 on 2025-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapchieuphim',
            old_name='lat',
            new_name='kinh_do',
        ),
        migrations.RenameField(
            model_name='rapchieuphim',
            old_name='lng',
            new_name='vi_do',
        ),
        migrations.RemoveField(
            model_name='rapchieuphim',
            name='hinh_anh',
        ),
        migrations.AlterField(
            model_name='rapchieuphim',
            name='dia_chi',
            field=models.TextField(),
        ),
    ]
