# Generated by Django 5.1.6 on 2025-04-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_lat_rapchieuphim_kinh_do_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phim', models.CharField(max_length=255)),
                ('the_loai', models.CharField(max_length=100)),
                ('thoi_luong', models.PositiveIntegerField(help_text='Thời lượng (phút)')),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GioChieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField()),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_chieu', to='maps.rapchieuphim')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_chieu', to='maps.phim')),
            ],
        ),
    ]
